Module 11
SamSeed-Softwire/DevOps-Course-Starter pull request #21
Opened 2021-04-29 09:09 UTC by SamSeed-Softwire

2021-05-07 14:23 UTC, hugh-emerson requested changes
Seems reasonable but there are two issues I'm unsure about:

The `SoftwirePilot_SamSeed_ProjectExercise` resource group only contains a DB. Where's your app service? I don't see any called `softwirepilot-samseed-projectexercise-app-service` which is what your Travis build seems to expect. I assume you did have it running at some point but if it's been deleted, can you recreate it?

Secondly, your commit says you've changed Travis to only build on pull requests. You don't want that - deployments will only happen for pushes to master. They don't (and shouldn't) run for pull requests.

2021-05-07 14:23 UTC, hugh-emerson commented on .travis.yml
> +    # TODO: cause Travis build to fail if the curl is unsuccessful.
This is a good idea but Travis ignores the exit code of after_deploy. So the correct solution may be a separate "stage".

Also, I'm not sure but you may need a short delay to really be sure you're hitting the latest version and it's had time to deploy.

2021-05-14 15:59 UTC, SamSeed-Softwire commented
Thanks @hugh-emerson. I think my app service got deleted when my free tier expired... I've recreated it using a new B1 tier app service plan (it wouldn't let me recreate a free tier app service plan, unsurprisingly!)

2021-05-14 16:00 UTC, SamSeed-Softwire commented on .travis.yml
> +    # TODO: cause Travis build to fail if the curl is unsuccessful.
Moving to a separate stage and putting the curl response check in a 'script' phase made this work, thanks for the idea! Also, Travis takes long enough to start a new stage that I essentially get a decent delay after the deployment for free.

2021-05-21 14:39 UTC, hugh-emerson approved these changes
Looks good! 👍

2021-05-21 14:39 UTC, hugh-emerson commented on .travis.yml
> +        branch: module_11
Don't forget to revert this

2021-06-04 12:09 UTC, merged